# Generated by Django 5.2.17 on 2026-09-01 08:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('challan_number', models.CharField(max_length=100)),
                ('challan_date', models.DateField()),
                ('delivery_source', models.CharField(blank=True, max_length=200)),
                ('bill_to_name', models.CharField(blank=True, max_length=200)),
                ('ship_to_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('needs_review', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('default_gst_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5)),
                ('po_number_hint', models.CharField(blank=True, max_length=200)),
                ('payment_terms_days', models.SmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('state_code', models.CharField(blank=True, max_length=2)),
                ('state_name', models.CharField(blank=True, max_length=100)),
                ('invoice_prefix', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('staff', 'Staff'), ('accounts', 'Accounts'), ('admin', 'Admin')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('force_password_change', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_role', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=60)),
                ('row_id', models.BigIntegerField()),
                ('action', models.CharField(max_length=10)),
                ('before_json', models.JSONField(blank=True, null=True)),
                ('after_json', models.JSONField(blank=True, null=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('filename', models.CharField(blank=True, max_length=300)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('rows_total', models.IntegerField(default=0)),
                ('rows_imported', models.IntegerField(default=0)),
                ('rows_flagged', models.IntegerField(default=0)),
                ('report_json', models.JSONField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(max_length=10)),
                ('reason_code', models.CharField(max_length=50)),
                ('source_ref', models.CharField(blank=True, max_length=200)),
                ('payload_json', models.JSONField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to='tracker.importbatch')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('bill_number', models.CharField(max_length=100)),
                ('bill_date', models.DateField()),
                ('basic_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('ariba_state', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('uploaded', 'Uploaded'), ('rejected', 'Rejected'), ('resubmitted', 'Resubmitted')], default='pending', max_length=20)),
                ('ariba_uploaded_on', models.DateField(blank=True, null=True)),
                ('ariba_reference', models.CharField(blank=True, max_length=100)),
                ('ariba_rejection_note', models.TextField(blank=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.legalentity')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('received_on', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('mode', models.CharField(blank=True, max_length=50)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('is_advance', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('kind', models.CharField(choices=[('payment', 'Payment'), ('tds', 'Tds'), ('retention', 'Retention'), ('discount', 'Discount'), ('write_off', 'Write Off')], default='payment', max_length=12)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.bill')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.payment')),
            ],
        ),
        migrations.CreateModel(
            name='POLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('line_no', models.IntegerField()),
                ('description', models.TextField()),
                ('item_type', models.CharField(choices=[('material', 'Material'), ('service', 'Service')], max_length=10)),
                ('qty_ordered', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit', models.CharField(max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('gst_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('work_done_on', models.DateField(blank=True, null=True)),
                ('client_approved_on', models.DateField(blank=True, null=True)),
                ('short_closed_on', models.DateField(blank=True, null=True)),
                ('short_close_reason', models.TextField(blank=True)),
                ('interim_status', models.CharField(blank=True, max_length=30)),
                ('source_sheet', models.CharField(blank=True, max_length=50)),
                ('source_row', models.IntegerField(blank=True, null=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('short_closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChallanAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='tracker.challan')),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challan_allocations', to='tracker.polineitem')),
            ],
        ),
        migrations.CreateModel(
            name='BillAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gst_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='tracker.bill')),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_allocations', to='tracker.polineitem')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('po_number', models.CharField(max_length=100)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('po_category', models.CharField(blank=True, max_length=100)),
                ('quotation_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('revision_reason', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('paste', 'Paste'), ('pdf', 'Pdf'), ('migration', 'Migration')], default='manual', max_length=12)),
                ('needs_review', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revision_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='tracker.purchaseorder')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tracker.purchaseorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='polineitem',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tracker.purchaseorder'),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='tracker.client')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.site'),
        ),
        migrations.AddField(
            model_name='challan',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.site'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('legal_entity', 'bill_number'), name='uq_bill_entity_number'),
        ),
        migrations.AddConstraint(
            model_name='challanallocation',
            constraint=models.UniqueConstraint(fields=('challan', 'line_item'), name='uq_challan_line'),
        ),
        migrations.AddConstraint(
            model_name='challanallocation',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='ck_challan_qty'),
        ),
        migrations.AddConstraint(
            model_name='billallocation',
            constraint=models.UniqueConstraint(fields=('bill', 'line_item'), name='uq_bill_line'),
        ),
        migrations.AddConstraint(
            model_name='billallocation',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='ck_bill_qty'),
        ),
        migrations.AddConstraint(
            model_name='polineitem',
            constraint=models.UniqueConstraint(fields=('po', 'line_no'), name='uq_line_po_no'),
        ),
        migrations.AddConstraint(
            model_name='polineitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty_ordered__gt', 0)), name='ck_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='polineitem',
            constraint=models.CheckConstraint(condition=models.Q(('gst_rate__gte', 0), ('gst_rate__lte', 1)), name='ck_gst_range'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('client', 'code'), name='uq_site_client_code'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('client', 'po_number'), name='uq_po_client_number'),
        ),
    ]
