# Generated by Django 5.2.17 on 2026-09-01
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('tracker', '0001_initial'), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.AddField(model_name='bill', name='created_by', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name='bill', name='source', field=models.CharField(choices=[('manual','Manual'),('paste','Paste'),('pdf','Pdf'),('migration','Migration')], default='manual', max_length=12)),
        migrations.AddField(model_name='challan', name='created_by', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name='challan', name='source', field=models.CharField(choices=[('manual','Manual'),('paste','Paste'),('pdf','Pdf'),('migration','Migration')], default='manual', max_length=12)),
        migrations.AddField(model_name='payment', name='created_by', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
        migrations.AddConstraint(model_name='challan', constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('challan_number','challan_date'), name='uq_challan_number_date')),
        migrations.AddConstraint(model_name='payment', constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_payment_positive')),
        migrations.AddConstraint(model_name='paymentallocation', constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_payment_allocation_positive')),
    ]
