export type Role = "owner" | "staff" | "accounts" | "admin"

export interface User { id: number; name: string; email: string; role?: Role; force_password_change?: boolean }
export interface LoginResponse { user: Omit<User, "role">; role: Role; force_password_change?: boolean }
export type LifecycleStage = "draft" | "ordered" | "partially_built" | "partially_paid" | "closed"
export interface LineItem { id?: number; line_no: number; description: string; item_type: "material" | "service"; qty_ordered: string; unit: string; rate: string; gst_rate: string; amount?: string; interim_status?: string; derived_status?: { status: string; qty_delivered: string; qty_billed: string }; needs_review?: boolean }
export interface PurchaseOrder { id: number; po_number: string; po_date: string; client_name: string; site_name?: string; status: string; lifecycle_stage: LifecycleStage; total_amount: string; amount_billed?: string; needs_review?: boolean; lines?: LineItem[]; line_items?: LineItem[]; notes?: string; updated_at?: string; totals?: { amount_ordered: string; amount_billed: string; amount_paid: string; outstanding_amount: string } }
export interface ReviewItem { id: number; severity: "error" | "warning"; reason_code: string; source_ref: string; payload_json: Record<string, string>; batch_id: number }
export interface Dashboard { metrics: { pending_items: number; outstanding_amount: string; overdue_bill_count: number; ariba_backlog_count: number }; stuck_items: Array<{ line_id: number; po_id: number; po_number: string; client: string; description: string; status: string; amount: string; days_waiting: number | null }>; overdue_bills: Array<{ bill_id: number; bill_number: string; client: string; outstanding_amount: string; age_days: number }>; ariba_backlog: Array<{ bill_id: number; bill_number: string; client: string; outstanding_amount: string; ariba_state: string; age_days: number }>; gst: { basic_billed: string; gst_billed: string; gross_billed: string } }
export interface Page<T> { count: number; results: T[] }
