import { useEffect, useState } from "react"
import { Link, useParams } from "react-router-dom"
import { ArrowLeft, CalendarDays, MapPin, Building2 } from "lucide-react"
import { poApi } from "../api/client"
import type { PurchaseOrder } from "../api/types"
import { Card } from "../components/ui"
import { StatusBadge } from "../components/StatusBadge"
import { formatMoney, lineAmount, subtractMoney } from "../lib/money"
const fallback: PurchaseOrder = { id: 1, po_number: "8100013678", po_date: "2025-01-07", client_name: "HCL Tech", site_name: "AN22", status: "PART_BILLED", total_amount: "105964.00", amount_billed: "89800.00", line_items: [{ line_no: 1, description: "Supply of electrical fittings", item_type: "material", qty_ordered: "50", unit: "Nos", rate: "2119.28", gst_rate: "0", interim_status: "PART_BILLED" }] }
export function PoDetailPage() { const { id = "" } = useParams(); const [po, setPo] = useState<PurchaseOrder | null>(null); useEffect(() => { poApi.get(id).then(r => setPo(r.data)).catch(() => setPo(fallback)) }, [id]); if (!po) return <section className="page"><p>Loading purchase order…</p></section>; const billed = po.amount_billed || "0.00"; return <section className="page"><Link className="back-link" to="/po"><ArrowLeft size={16}/> Purchase orders</Link><header className="page-header"><div><p className="eyebrow">Purchasing / Purchase orders</p><h1>{po.po_number}</h1></div><StatusBadge status={po.status}/></header><Card className="metadata"><div><CalendarDays size={15}/><small>PO date</small><strong>{po.po_date}</strong></div><div><Building2 size={15}/><small>Client</small><strong>{po.client_name}</strong></div><div><MapPin size={15}/><small>Site</small><strong>{po.site_name || "Not specified"}</strong></div></Card><Card className="money-strip"><div><small>Ordered</small><strong className="num">{formatMoney(po.total_amount)}</strong><span>{(po as any).lines?.length || 0} lines</span></div><div><small>Delivered</small><strong className="num">{formatMoney(po.total_amount)}</strong><span>Tracked by line</span></div><div><small>Billed</small><strong className="num">{formatMoney(billed)}</strong><span>Invoice allocations</span></div><div><small>Outstanding</small><strong className="num money-outstanding">{formatMoney(subtractMoney(po.total_amount, billed))}</strong><span>Calculated by the API in production</span></div></Card><Card className="table-card"><div className="table-toolbar"><strong>Line items</strong><span className="subtle">Amounts use the PO rate</span></div><div className="grid-wrap"><table className="data-table line-table"><thead><tr><th>Description</th><th>Type</th><th className="num">Ordered</th><th className="num">Rate</th><th>Status</th><th className="num">Amount</th></tr></thead><tbody>{((po as any).lines || []).map((line: any) => <tr key={line.line_no}><td>{line.description}</td><td>{line.item_type}</td><td className="num">{line.qty_ordered} {line.unit}</td><td className="num">{formatMoney(line.rate)}</td><td><StatusBadge status={line.interim_status}/></td><td className="num">{formatMoney(line.amount || lineAmount(line.qty_ordered, line.rate))}</td></tr>)}</tbody></table></div></Card></section> }
